### ISSUE TITLE
missing config.iss

### ISSUE THREAD

**Issue by michlalp** [johnstevenson/pl2303-legacy#2]
Hello John,
thank you for this driver, but it seems that config.iss is missing so Innosetup cannot compile.

**Comment by johnstevenson** [comment]
You either have to provide your own config.iss or pass the required parameters on the command-line. The latter method is how the build workflow runs:

https://github.com/johnstevenson/pl2303-legacy/blob/d5e022802b4bdbd051c17d98bc8217487070a935/.github/workflows/build.yml#L23
