### ISSUE TITLE
Device not connected on Windows 11

### ISSUE THREAD

**Issue by hableel** [johnstevenson/pl2303-legacy#6]
Hello,

Im getting "Device not connected" message, on windows 11 using 1.1.0 release.

OS info:

OsName                    OsVersion  OsBuildNumber

Microsoft Windows 11 Home 10.0.22000 22000

Device info, using the command `pnputil.exe /enum-devices /drivers /connected`

Instance ID:                USB\VID_067B&PID_2303\6&279c56a4&0&7
Device Description:         USB-Serial Controller D
Class Name:                 Unknown
Class GUID:                 Unknown
Manufacturer Name:          Unknown
Status:                     Problem
Problem Code:               28 (0x1C) [CM_PROB_FAILED_INSTALL]
Problem Status:             0xC0000490

**Comment by johnstevenson** [comment]
Thanks for the detailed report.

Could you please tell me more about the device you are connecting. I presume it contains a Prolific PL2303 chip and you have installed a driver?

Please run `pnputil.exe /enum-drivers /class Ports` and show me the details where _Provider Name_ is Prolific.

**Comment by hableel** [comment]
Thank you for your reponse.

Im trying to investigate an issue with Mosconi DSP becuase it stopped working correctly, and I dont know if it is a hardware or software problem. 

After seaching the hardware id, it looks like it has pl2303 chip.

Hardware Id:
USB\VID_067B&PID_2303&REV_0400

After running the command, I found 5 results:


Published Name:     oem128.inf
Original Name:      plser_1.inf
Provider Name:      Prolific
Class Name:         Ports (COM & LPT)
Class GUID:         {4d36e978-e325-11ce-bfc1-08002be10318}
Driver Version:     06/07/2024 5.2.7.0
Signer Name:        Microsoft Windows Hardware Compatibility Publisher

Published Name:     oem130.inf
Original Name:      plser_1.inf
Provider Name:      Prolific
Class Name:         Ports (COM & LPT)
Class GUID:         {4d36e978-e325-11ce-bfc1-08002be10318}
Driver Version:     12/03/2021 5.2.2.0
Signer Name:        Microsoft Windows Hardware Compatibility Publisher

Published Name:     oem126.inf
Original Name:      ser2pl.inf
Provider Name:      Prolific
Class Name:         Ports (COM & LPT)
Class GUID:         {4d36e978-e325-11ce-bfc1-08002be10318}
Driver Version:     02/05/2013 3.4.48.272
Signer Name:        Microsoft Windows Hardware Compatibility Publisher

Published Name:     oem131.inf
Original Name:      ser2pl_1.inf
Provider Name:      Prolific
Class Name:         Ports (COM & LPT)
Class GUID:         {4d36e978-e325-11ce-bfc1-08002be10318}
Driver Version:     02/18/2022 3.9.1.0
Signer Name:        Microsoft Windows Hardware Compatibility Publisher

Published Name:     oem129.inf
Original Name:      ser2pl_1.inf
Provider Name:      Prolific
Class Name:         Ports (COM & LPT)
Class GUID:         {4d36e978-e325-11ce-bfc1-08002be10318}
Driver Version:     06/17/2024 3.9.6.0
Signer Name:        Microsoft Windows Hardware Compatibility Publisher

**Comment by hableel** [comment]
I am closing the issue as the device is recognized using Windows 10.
