### ISSUE TITLE
Windows 10: Driver configuration not persistent

### ISSUE THREAD

**Issue by SamGinrich** [johnstevenson/pl2303-legacy#7]
COM Interface works fine after unsintalling default outdated windows driver and deploying PL2303LegacyUpdaterSetup-1.1.0.exe,
in my case for a PL2303HXA . 

Thank you for provding this feature!

Though after system restart windows again binds some outdated driver and the COM interface is not active.

How to prevent this behavior?

**Comment by johnstevenson** [comment]
> How to prevent this behavior?

You can't. That's why we recommend that you install this program so you can easily run it again when needed.
